import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./navbar/Navbar";
import Footer from "./footer/Footer";
import localFont from "next/font/local";

const sfPro = localFont({
  src: [
    { path: "./../public/fonts/sfpro/SFPRODISPLAYREGULAR.woff2", weight: "400", style: "normal" },
    { path: "./../public/fonts/sfpro/SFPRODISPLAYMEDIUM.woff2", weight: "500", style: "normal" },
    { path: "./../public/fonts/sfpro/SFPRODISPLAYBOLD.woff2", weight: "700", style: "normal" },
  ],
  variable: "--font-sf-pro",
});

export const metadata: Metadata = {
  title: "Fitnest",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${sfPro.className} antialiased`}
      >
        <div className="flex flex-col p-5 lg:px-18 md:py-10 min-h-screen bg-softblue-1000">
          <Navbar />
          <main className="grow w-full ">
            {children}
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
