import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import icon from '@/public/Logo.png'

const sfPro = localFont({
  src: [
    { path: "./../public/fonts/sfpro/SFPRODISPLAYREGULAR.woff2", weight: "400", style: "normal" },
    { path: "./../public/fonts/sfpro/SFPRODISPLAYMEDIUM.woff2", weight: "500", style: "normal" },
    { path: "./../public/fonts/sfpro/SFPRODISPLAYBOLD.woff2", weight: "700", style: "normal" },
  ],
  variable: "--font-sf-pro",
});

export const metadata: Metadata = {
  title: "Fitnest",
  description: "Generated by create next app",
  icons: icon.src
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${sfPro.className} antialiased`}
      >
       {children}
      </body>
    </html>
  );
}
