import type { Metadata } from "next";
import Navbar from "../navbar/Navbar";
import Footer from "../footer/Footer";

export const metadata: Metadata = {
  title: "Fitnest",
  description: "Generated by create next app",
};

export default function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <div className="flex flex-col w-full  min-h-screen bg-softblue-1000">
        <Navbar />
        <main className="grow flex flex-col w-full  mx-auto">{children}</main>
      </div>
      <Footer />
    </>
  );
}
