import type { Metadata } from "next";




export const metadata: Metadata = {
  title: "Fitnest",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <div>{ children }</div>;
}
