import type { Metadata } from "next";
import Navbar from "../navbar/Navbar";
import Footer from "../footer/Footer";

export const metadata: Metadata = {
  title: "Fitnest",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="bg-softblue-1000 min-h-screen">
      <Navbar />
      {children}
      <Footer />
    </div>
  );
}
